spring.application.name=loan-tracking-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/loan-tracking-system
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.servlet.multipart.max-file-size=10MB
spring.jpa.hibernate.ddl-auto=update
server.tomcat.max-part-count=50
server.tomcat.max-part-header-size=2048