spring.application.name=loan-tracking-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/loan-tracking-system
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update